version: "3.8"

services:
  db:
    image: postgres:15
    container_name: zoop-db 
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres-db/data:/var/lib/postgresql/data
      - ./postgres-db/init:/docker-entrypoint-initdb.d